In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys
sys.path.append("../../")
from src.config_unitelma import CLASSIFIERS

from src.ml_pipeline import MLPipeline
from src.dl_pipeline import DLPipeline
import warnings
warnings.filterwarnings("ignore")

from dotenv import load_dotenv
load_dotenv()

TRAIN_PATH = os.path.join(os.getenv("UNITELMA_DATA"), "train_timeseries.csv")
TEST_PATH = os.path.join(os.getenv("UNITELMA_DATA"), "test_timeseries.csv")
OUTPUT_DIR = os.path.join(os.getenv("ROOT_DIR"), "notebooks_unitelma/runs/outputs")

LAGS_TO_TEST = [7, 14]

/Volumes/T7/documents/github/dropout-prediction/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Unitelma

In [3]:
ml_processor = MLPipeline(
    train_path=TRAIN_PATH, 
    test_path=TEST_PATH, 
    output_path=OUTPUT_DIR, 
    use_macro=False
)

df_ml_results = ml_processor.run(
    lags=LAGS_TO_TEST,
    classifiers=CLASSIFIERS,
    apply_clipping=False,
    use_fs=False,
    time_aggregation='flatten'
)

display(df_ml_results)

[INFO] Device: mps

[INFO] PIPELINE ML | Lag: 7
[TRAIN] LogisticRegression...
[TRAIN] RandomForest...

[INFO] PIPELINE ML | Lag: 14
[TRAIN] LogisticRegression...
[TRAIN] RandomForest...

[SUCCESS] CSV saved in: /Volumes/T7/documents/github/dropout-prediction/notebooks_unitelma/runs/outputs/metrics_ml_20260531_224847.csv

,accuracy,precision,recall,f1,roc_auc,pr_auc,lag,algorithm,time_agg,use_macro,use_fs
0,0.7122,0.6980,0.7122,0.7047,0.5710,0.7086,7,LogisticRegression,flatten,False,False
1,0.6831,0.7835,0.6831,0.7118,0.7310,0.7920,7,RandomForest,flatten,False,False
2,0.7277,0.6934,0.7277,0.7081,0.5417,0.6990,14,LogisticRegression,flatten,False,False
3,0.7064,0.7560,0.7064,0.7251,0.7274,0.7945,14,RandomForest,flatten,False,False

In [7]:
dl_processor = DLPipeline(
    train_path=TRAIN_PATH, 
    test_path=TEST_PATH, 
    output_path=OUTPUT_DIR, 
    use_macro=False
)

df_dl_results = dl_processor.run(
    lags=LAGS_TO_TEST,
    apply_clipping=False
)

display(df_dl_results)

[INFO] Device: mps

[INFO] PIPELINE DL (LSTM) | Lag: 7
[TRAIN] LSTM (Epochs: 30, Hidden: 64)

[INFO] PIPELINE DL (LSTM) | Lag: 14
[TRAIN] LSTM (Epochs: 30, Hidden: 64)

[SUCCESS] CSV saved in: /Volumes/T7/documents/github/dropout-prediction/notebooks_unitelma/runs/outputs/metrics_dl_20260531_225405.csv

,accuracy,precision,recall,f1,roc_auc,pr_auc,lag,algorithm,use_macro,epochs,batch_size,hidden_dim,lr
0,0.6114,0.7947,0.6114,0.6483,0.7070,0.7843,7,LSTM,False,30,64,64,0.001
1,0.6599,0.8035,0.6599,0.6927,0.7405,0.7959,14,LSTM,False,30,64,64,0.001